export const countries = [
  {
    value: "US",
    label: "United States",
    phoneCode: "+1",
    currencyCode: "USD",
    countryCode: "US",
    flag: "🇺🇸",
  },
  {
    value: "IN",
    label: "India",
    phoneCode: "+91",
    currencyCode: "INR",
    countryCode: "IN",
    flag: "🇮🇳",
  },
  {
    value: "GB",
    label: "United Kingdom",
    phoneCode: "+44",
    currencyCode: "GBP",
    countryCode: "GB",
    flag: "🇬🇧",
  },
  {
    value: "CA",
    label: "Canada",
    phoneCode: "+1",
    currencyCode: "CAD",
    countryCode: "CA",
    flag: "🇨🇦",
  },
  {
    value: "AU",
    label: "Australia",
    phoneCode: "+61",
    currencyCode: "AUD",
    countryCode: "AU",
    flag: "🇦🇺",
  },
  {
    value: "DE",
    label: "Germany",
    phoneCode: "+49",
    currencyCode: "EUR",
    countryCode: "DE",
    flag: "🇩🇪",
  },
  {
    value: "FR",
    label: "France",
    phoneCode: "+33",
    currencyCode: "EUR",
    countryCode: "FR",
    flag: "🇫🇷",
  },
  {
    value: "JP",
    label: "Japan",
    phoneCode: "+81",
    currencyCode: "JPY",
    countryCode: "JP",
    flag: "🇯🇵",
  },
  {
    value: "CN",
    label: "China",
    phoneCode: "+86",
    currencyCode: "CNY",
    countryCode: "CN",
    flag: "🇨🇳",
  },
  {
    value: "BR",
    label: "Brazil",
    phoneCode: "+55",
    currencyCode: "BRL",
    countryCode: "BR",
    flag: "🇧🇷",
  },
  {
    value: "ZA",
    label: "South Africa",
    phoneCode: "+27",
    currencyCode: "ZAR",
    countryCode: "ZA",
    flag: "🇿🇦",
  },
  {
    value: "RU",
    label: "Russia",
    phoneCode: "+7",
    currencyCode: "RUB",
    countryCode: "RU",
    flag: "🇷🇺",
  },
  {
    value: "MX",
    label: "Mexico",
    phoneCode: "+52",
    currencyCode: "MXN",
    countryCode: "MX",
    flag: "🇲🇽",
  },
  {
    value: "KR",
    label: "South Korea",
    phoneCode: "+82",
    currencyCode: "KRW",
    countryCode: "KR",
    flag: "🇰🇷",
  },
  {
    value: "ES",
    label: "Spain",
    phoneCode: "+34",
    currencyCode: "EUR",
    countryCode: "ES",
    flag: "🇪🇸",
  },
  {
    value: "IT",
    label: "Italy",
    phoneCode: "+39",
    currencyCode: "EUR",
    countryCode: "IT",
    flag: "🇮🇹",
  },
  {
    value: "NL",
    label: "Netherlands",
    phoneCode: "+31",
    currencyCode: "EUR",
    countryCode: "NL",
    flag: "🇳🇱",
  },
  {
    value: "SE",
    label: "Sweden",
    phoneCode: "+46",
    currencyCode: "SEK",
    countryCode: "SE",
    flag: "🇸🇪",
  },
  {
    value: "CH",
    label: "Switzerland",
    phoneCode: "+41",
    currencyCode: "CHF",
    countryCode: "CH",
    flag: "🇨🇭",
  },
  {
    value: "TR",
    label: "Turkey",
    phoneCode: "+90",
    currencyCode: "TRY",
    countryCode: "TR",
    flag: "🇹🇷",
  },
  {
    value: "SA",
    label: "Saudi Arabia",
    phoneCode: "+966",
    currencyCode: "SAR",
    countryCode: "SA",
    flag: "🇸🇦",
  },
  {
    value: "AE",
    label: "United Arab Emirates",
    phoneCode: "+971",
    currencyCode: "AED",
    countryCode: "AE",
    flag: "🇦🇪",
  },
  {
    value: "AR",
    label: "Argentina",
    phoneCode: "+54",
    currencyCode: "ARS",
    countryCode: "AR",
    flag: "🇦🇷",
  },
  {
    value: "NG",
    label: "Nigeria",
    phoneCode: "+234",
    currencyCode: "NGN",
    countryCode: "NG",
    flag: "🇳🇬",
  },
  {
    value: "ID",
    label: "Indonesia",
    phoneCode: "+62",
    currencyCode: "IDR",
    countryCode: "ID",
    flag: "🇮🇩",
  },
  {
    value: "PL",
    label: "Poland",
    phoneCode: "+48",
    currencyCode: "PLN",
    countryCode: "PL",
    flag: "🇵🇱",
  },
  {
    value: "BE",
    label: "Belgium",
    phoneCode: "+32",
    currencyCode: "EUR",
    countryCode: "BE",
    flag: "🇧🇪",
  },
  {
    value: "PH",
    label: "Philippines",
    phoneCode: "+63",
    currencyCode: "PHP",
    countryCode: "PH",
    flag: "🇵🇭",
  },
  {
    value: "TH",
    label: "Thailand",
    phoneCode: "+66",
    currencyCode: "THB",
    countryCode: "TH",
    flag: "🇹🇭",
  },
  {
    value: "MY",
    label: "Malaysia",
    phoneCode: "+60",
    currencyCode: "MYR",
    countryCode: "MY",
    flag: "🇲🇾",
  },
  {
    value: "PT",
    label: "Portugal",
    phoneCode: "+351",
    currencyCode: "EUR",
    countryCode: "PT",
    flag: "🇵🇹",
  },
  {
    value: "IE",
    label: "Ireland",
    phoneCode: "+353",
    currencyCode: "EUR",
    countryCode: "IE",
    flag: "🇮🇪",
  },
]

